function(_praxis_append_property TARGET PROPERTY LIST_VAR)
    get_target_property(value ${TARGET} ${PROPERTY})
    if (value)
        list(APPEND ${LIST_VAR} ${value})
        set(${LIST_VAR} "${${LIST_VAR}}" PARENT_SCOPE)
    endif ()
endfunction()

function(_praxis_interface_include_closure TARGET OUT_DIRS)
    set(pending "${TARGET}")
    set(seen "")
    set(dirs "")
    while (pending)
        list(POP_FRONT pending current)
        if (NOT TARGET "${current}" OR current IN_LIST seen)
            continue()
        endif ()
        list(APPEND seen "${current}")
        get_target_property(aliased ${current} ALIASED_TARGET)
        if (aliased)
            list(APPEND pending "${aliased}")
            continue()
        endif ()
        _praxis_append_property(${current} INTERFACE_INCLUDE_DIRECTORIES dirs)
        _praxis_append_property(${current} INTERFACE_LINK_LIBRARIES pending)
    endwhile ()
    set(${OUT_DIRS} "${dirs}" PARENT_SCOPE)
endfunction()

# Catches an include-directory leak that carries no link edge, which the link-graph closure check
# structurally cannot see.
function(praxis_assert_no_include_leak TARGET)
    _praxis_interface_include_closure(${TARGET} dirs)
    foreach (dir IN LISTS dirs)
        foreach (fragment IN LISTS ARGN)
            string(FIND "${dir}" "${fragment}" position)
            if (NOT position EQUAL -1)
                message(FATAL_ERROR
                    "praxis: ${TARGET} exposes the include directory '${dir}', which matches the "
                    "forbidden path fragment '${fragment}'")
            endif ()
        endforeach ()
    endforeach ()
endfunction()
