# A declaration is identified by the header it was read from, the name it declares and the kind of
# declaration it is; its signature and the type it answers are what a re-signature changes. The key
# is taken as the first three fields rather than by dropping the trailing ones, so that a row
# recorded before the return type was carried compares equal to one extracted after it.
function(praxis_surface_identity ROW OUT)
    string(ASCII 9 tab)
    string(REGEX MATCH "^[^${tab}]*${tab}[^${tab}]*${tab}[^${tab}]*" identity "${ROW}")
    set(${OUT} "${identity}" PARENT_SCOPE)
endfunction()

function(praxis_surface_identities LIST_VAR OUT)
    set(identities "")
    foreach (declaration IN LISTS ${LIST_VAR})
        praxis_surface_identity("${declaration}" identity)
        list(APPEND identities "${identity}")
    endforeach ()
    set(${OUT} "${identities}" PARENT_SCOPE)
endfunction()

# An identity is not a key: overloads of one name, and the several constructors a type declares,
# each carry the same header, name and kind, so a record holds as many rows of an identity as there
# are declarations sharing it. A declaration is new where the extraction carries one more row of its
# identity than the record does, and gone where the record carries one more than the extraction,
# which is a count on both sides rather than a presence.
function(praxis_identity_count VALUE LIST_VAR OUT)
    set(count 0)
    foreach (entry IN LISTS ${LIST_VAR})
        if (entry STREQUAL "${VALUE}")
            math(EXPR count "${count} + 1")
        endif ()
    endforeach ()
    set(${OUT} "${count}" PARENT_SCOPE)
endfunction()

# A recorded row the extraction does not carry is charged against its identity's shortfall: the
# first such rows up to the shortfall are the declarations that went away, and any beyond it are
# rows whose identity survives at a different signature.
function(praxis_surface_departures RECORDED_VAR EXTRACTED_VAR RECORDED_IDS_VAR EXTRACTED_IDS_VAR RESIGNATURED_OUT REMOVED_OUT)
    set(resignatured "")
    set(removed "")
    set(charged_identities "")
    foreach (declaration IN LISTS ${RECORDED_VAR})
        if (NOT declaration IN_LIST ${EXTRACTED_VAR})
            praxis_surface_identity("${declaration}" identity)
            praxis_identity_count("${identity}" ${EXTRACTED_IDS_VAR} extracted_rows)
            praxis_identity_count("${identity}" ${RECORDED_IDS_VAR} recorded_rows)
            praxis_identity_count("${identity}" charged_identities charged_rows)
            math(EXPR shortfall "${recorded_rows} - ${extracted_rows}")
            if (charged_rows LESS shortfall)
                list(APPEND removed "${declaration}")
                list(APPEND charged_identities "${identity}")
            else ()
                list(APPEND resignatured "${declaration}")
            endif ()
        endif ()
    endforeach ()
    set(${RESIGNATURED_OUT} "${resignatured}" PARENT_SCOPE)
    set(${REMOVED_OUT} "${removed}" PARENT_SCOPE)
endfunction()

# An extracted row the record does not carry is listed only up to its identity's surplus; the rest
# are the other side of a re-signature and are already reported as such.
function(praxis_surface_arrivals RECORDED_VAR EXTRACTED_VAR RECORDED_IDS_VAR EXTRACTED_IDS_VAR ADDED_OUT)
    set(added "")
    set(listed_identities "")
    foreach (declaration IN LISTS ${EXTRACTED_VAR})
        if (NOT declaration IN_LIST ${RECORDED_VAR})
            praxis_surface_identity("${declaration}" identity)
            praxis_identity_count("${identity}" ${EXTRACTED_IDS_VAR} extracted_rows)
            praxis_identity_count("${identity}" ${RECORDED_IDS_VAR} recorded_rows)
            praxis_identity_count("${identity}" listed_identities listed_rows)
            math(EXPR surplus "${extracted_rows} - ${recorded_rows}")
            if (listed_rows LESS surplus)
                list(APPEND added "${declaration}")
                list(APPEND listed_identities "${identity}")
            endif ()
        endif ()
    endforeach ()
    set(${ADDED_OUT} "${added}" PARENT_SCOPE)
endfunction()

function(praxis_surface_listing LABEL LIST_VAR REPORT_VAR)
    if (${LIST_VAR})
        list(JOIN ${LIST_VAR} "\n      " listing)
        string(APPEND ${REPORT_VAR} "\n  ${LABEL}:\n      ${listing}")
    else ()
        string(APPEND ${REPORT_VAR} "\n  ${LABEL}: none")
    endif ()
    set(${REPORT_VAR} "${${REPORT_VAR}}" PARENT_SCOPE)
endfunction()

function(praxis_surface_message RESIGNATURED_VAR REMOVED_VAR ADDED_VAR DIVERGENCE OUT)
    set(report "praxis: the shipped public surface no longer matches its record.")
    praxis_surface_listing("re-signatured" ${RESIGNATURED_VAR} report)
    praxis_surface_listing("removed" ${REMOVED_VAR} report)
    praxis_surface_listing("added" ${ADDED_VAR} report)
    if (DIVERGENCE)
        string(APPEND report "\n  order diverges ${DIVERGENCE}")
    else ()
        string(APPEND report "\n  order: unchanged")
    endif ()
    set(${OUT} "${report}" PARENT_SCOPE)
endfunction()

function(praxis_surface_report RECORDED_VAR EXTRACTED_VAR DIVERGENCE)
    praxis_surface_identities(${RECORDED_VAR} recorded_identities)
    praxis_surface_identities(${EXTRACTED_VAR} extracted_identities)
    praxis_surface_departures(${RECORDED_VAR} ${EXTRACTED_VAR} recorded_identities extracted_identities resignatured removed)
    praxis_surface_arrivals(${RECORDED_VAR} ${EXTRACTED_VAR} recorded_identities extracted_identities added)
    if (NOT resignatured AND NOT removed AND NOT added AND NOT DIVERGENCE)
        return()
    endif ()
    praxis_surface_message(resignatured removed added "${DIVERGENCE}" report)
    message(FATAL_ERROR "${report}")
endfunction()
